package Simori;
public enum Modes {
	ONOFFMODE, PERFORMANCEMODE, CHANGEVOICEMODE, CHANGEVELOCITYMODE, CHANGELOOPSPEEDMODE,
	CHANGELOOPPOINTMODE, CHANGELAYERMODE, SAVECONFIGURATIONMODE, LOADCONFIGURATIONMODE, 
	SLAVEMASTERMODE, SHOPBOYMODE
}
